name: Update Version Number

on:
  push:
    paths:
      - 'quizbot.luau'
  pull_request:
    paths:
      - 'quizbot.luau'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract version and update file
        run: |
          # Extract version number from first line of quizbot.luau
          VERSION=$(head -n 1 quizbot.luau | grep -o '"[^"]*"' | tail -1 | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
          # Create or update version_number.luau
          echo "return \"$VERSION\"" > version_number.luau
          
          # Check if there are changes to commit
          if git diff --quiet version_number.luau; then
            echo "No changes to version number"
            echo "changes_detected=false" >> $GITHUB_ENV
            exit 0
          else
            echo "changes_detected=true" >> $GITHUB_ENV
          fi
      - name: Commit changes
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add version_number.luau
          git commit -m "[VERSION] Bump version number to ${{ env.VERSION }}"
          git push
